<?php

use \PHPUnit\Framework\TestCase;
require "FizzBuzz.php";

class FizzBuzzTest extends TestCase
{
    private $fizzBuzz;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fizzBuzz = new FizzBuzz();
    }

    public function testSample() {
        //Arrange

        //Act

        //Assert
        $this->assertTrue(true);
    }

    public function test_count_given1_shouldReturn1() {
        $actual =$this->actCount(1);

        //Assert
        $this->assertEquals("1", $actual);
    }

    public function test_count_given2_shouldReturn2() {
        $actual = $this->actCount(2);

        $this->assertEquals("2", $actual);
    }

    public function test_count_given3_shouldReturnFizz() {
        $actual = $this->actCount(3);

        $this->assertEquals("Fizz", $actual);
    }

    public function test_count_given5_shouldReturnBuzz() {
        $actual = $this->actCount(5);

        $this->assertEquals("Buzz", $actual);
    }

    public function test_count_given6_shouldReturnBuzz() {
        $actual = $this->actCount(6);

        $this->assertEquals("Fizz", $actual);
    }

    /**
     * @return mixed
     */
    public function actCount(int $int): string
    {
        return $this->fizzBuzz->count($int);
    }
}
